let adjective = "silly";
let noun = "robot";
let verb = "dance";
let place = "the moon";
let adjective2 = "sparking";
let noun2 = "banana";
let firstStory = "Once upon a time, there was a(n) " + adjective  + " " + noun + " who loved to eat " + noun2 + ". The " + noun + " lived in a " + place + " and had " + adjective2 +" nostrils that blew fire when it was " + verb + ".";
console.log("First story: "  + firstStory);
adjective = "clumsy";
noun = "octopus;"
verb = "giggle";
place = "a submarine";
adjective2 = "glittering";
noun2 = "waffles";
let secondStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + ". The " + noun + " lived in a " + place + " and had " + adjective2 + " nostrils that blew fire when it was " + verb + ".";
console.log("Second story: " + secondStory);